=== vittau/PPAL/Examples/DEL.dtd
<!ELEMENT model (agentsdef+, propositions+, restrictions*, realstate)>
<!ATTLIST model
    version CDATA #REQUIRED
    name CDATA #IMPLIED>
<!ELEMENT agentsdef (a)+>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a
    id CDATA #REQUIRED
    prefix CDATA #REQUIRED>
<!ELEMENT propositions (generic)+>
<!ELEMENT generic (name, agents)+>
<!ATTLIST generic
    id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT agents (#PCDATA)>
<!ELEMENT restrictions (rule|mutex)+>
<!ELEMENT rule (#PCDATA)>
<!ELEMENT mutex (#PCDATA)>
<!ELEMENT realstate (#PCDATA)>

=== vittau/PPAL/Examples/DELExample.xml
<?xml version="1.0"?>
<!DOCTYPE model SYSTEM "DEL.dtd">
<model version="0.4" name="Cards game">
	<!-- Cards game example. Using the DEL DTD. -->
	<agentsdef>
		<a id="A" prefix="A">Alice</a>
		<a id="B" prefix="B">Bob</a>
		<a id="C" prefix="C">Carol</a>
	</agentsdef>

	<propositions>
		<generic id="has0">
			<name>AGENT.pre has 0</name>
			<agents>A and B and C</agents>
		</generic>
		<generic id="has1">
			<name>AGENT.pre has 1</name>
			<agents>A and B and C</agents>
		</generic>
		<generic id="has2">
			<name>AGENT.pre has 2</name>
			<agents>A and B and C</agents>
		</generic>
	</propositions>

	<restrictions>

		<!-- Agents must have at least one card -->
		<rule>!AGENT.has0 and !AGENT.has1 and !AGENT.has2</rule>
		<!-- Agents must have at most one card -->
		<mutex>AGENT.has0 and AGENT.has1 and AGENT.has2</mutex>
		<!-- ...Therefore, agents have exactly one card -->

		<!-- Different agents can't have the same card -->
		<mutex>AGENT_0.has0 and AGENT_1.has0</mutex>
	</restrictions>

	<realstate>A.has0 and B.has1 and C.has2</realstate>

</model>
